name: phonics
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.5.4







dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.2.3

  
  
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter_sound: ^9.28.0
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  audio_session: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
  
  
  flutter_lints: ^5.0.0
  flutter_dash: ^1.0.0





flutter:

  
  
  
  uses-material-design: true

  
  assets:
    - assets/images/
    - assets/images/words/
    - assets/images/mypage/
    - assets/images/core/
    - assets/navigation_icons/
  fonts:
    - family: GyeonggiBatangBold
      fonts:
        - asset: fonts/GyeonggiBatang_Bold.ttf
    - family: GyeonggiBatangRegular
      fonts:
        - asset: fonts/GyeonggiBatang_Regular.ttf
    - family: GyeonggiTitleLight
      fonts:
        - asset: fonts/GyeonggiTitle_Light.ttf
    - family: GyeonggiTitleMedium
      fonts:
        - asset: fonts/GyeonggiTitle_Medium.ttf
    - family: GyeonggiTitleBold
      fonts:
        - asset: fonts/GyeonggiTitle_Bold.ttf
    - family: GyeonggiTitleVBold
      fonts:
        - asset: fonts/GyeonggiTitleV_Bold.ttf

    

  

  
  

  
  

  
  
  
  
  


  
  
  
  
  
  
  
  
  
  
  
  
  
