name: phonics
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  audio_session: ^0.2.2
  cupertino_icons: ^1.0.8
  dropdown_button2: ^2.3.9
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.2.1
  flutter_riverpod: ^2.6.1
  flutter_sound: ^9.28.0
  flutter_tts: ^4.2.3
  go_router: ^16.1.0
  google_sign_in: ^7.1.1
  http: ^1.5.0
  kakao_flutter_sdk: ^1.9.7+3
  kakao_flutter_sdk_user: ^1.9.7+3
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.5.3
  url_strategy: ^0.3.0

dev_dependencies:
  flutter_dash: ^1.0.0

  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/words/
    - assets/images/mypage/
    - assets/images/core/
    - assets/navigation_icons/
  fonts:
    - family: GyeonggiBatangBold
      fonts:
        - asset: fonts/GyeonggiBatang_Bold.ttf
    - family: GyeonggiBatangRegular
      fonts:
        - asset: fonts/GyeonggiBatang_Regular.ttf
    - family: GyeonggiTitleLight
      fonts:
        - asset: fonts/GyeonggiTitle_Light.ttf
    - family: GyeonggiTitleMedium
      fonts:
        - asset: fonts/GyeonggiTitle_Medium.ttf
    - family: GyeonggiTitleBold
      fonts:
        - asset: fonts/GyeonggiTitle_Bold.ttf
    - family: GyeonggiTitleVBold
      fonts:
        - asset: fonts/GyeonggiTitleV_Bold.ttf
